# This script is based on https://github.com/big-data-europe/docker-hadoop
FROM calvalusmarine/hadoop-base:master

HEALTHCHECK CMD curl -f http://localhost:8188/ || exit 1

ADD run.sh /run.sh
RUN chmod a+x /run.sh

EXPOSE 19888

CMD ["/run.sh"]
